fix: don't parse the header as a symbol
Without this patch, attempting to run `check` throws:
```
Error: failed to construct FunctionChecker

Caused by:
    invalid digit found in string
```

A quick check by printing inside parse_address shows that it's attempting to parse "Address" as an address, meaning it's attempting to parse the CSV header as a symbol.